### ISSUE TITLE
leveldb: OutPredicates().All() causes panic

### ISSUE THREAD

**Issue by d4l3k** [cayleygraph/cayley#437]
Running this query through the HTTP interface causes cayley to panic when using leveldb.
```
g.V('story:AO3:4468').OutPredicates().All()
```

Stack trace
```
 ✘  ~/go/src/github.com/d4l3k/ficrecommend   master ●  cayley http -db leveldb -dbpath ./recommender.leveldb
Cayley now listening on 127.0.0.1:64210
panic: runtime error: hash of unhashable type leveldb.Token [recovered]
	panic: runtime error: hash of unhashable type leveldb.Token [recovered]
	panic: runtime error: hash of unhashable type leveldb.Token

goroutine 19 [running]:
panic(0x8b0a60, 0xc820347080)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
github.com/google/cayley/query/gremlin.(*Session).runUnsafe.func1(0xc82005e0e0, 0xc8202dbb30)
	/Users/wiz/go/src/github.com/google/cayley/query/gremlin/session.go:100 +0x136
panic(0x8b0a60, 0xc820347080)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:443 +0x4e9
github.com/robertkrimen/otto.catchPanic.func1(0xc820343cd8)
	/Users/wiz/go/src/github.com/robertkrimen/otto/error.go:247 +0x7b9
panic(0x8b0a60, 0xc820347080)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:443 +0x4e9
github.com/google/cayley/graph/iterator.(*Unique).Next(0xc82007c240, 0x138c590)
	/Users/wiz/go/src/github.com/google/cayley/graph/iterator/unique_iterator.go:77 +0x196
github.com/google/cayley/graph.Next(0x138c590, 0xc82007c240, 0xc820333080)
	/Users/wiz/go/src/github.com/google/cayley/graph/iterator.go:190 +0x89
github.com/google/cayley/query/gremlin.(*worker).runIterator(0xc8202dbb30, 0x138c590, 0xc82007c240)
	/Users/wiz/go/src/github.com/google/cayley/query/gremlin/finals.go:295 +0x30a
github.com/google/cayley/query/gremlin.(*worker).allFunc.func1(0xc82008a480, 0x0, 0x0, 0x5, 0x98da20, 0xc82034e7e0, 0xeaaad8, 0x0, 0x0, 0xc8201e9350, ...)
	/Users/wiz/go/src/github.com/google/cayley/query/gremlin/finals.go:46 +0x121
github.com/robertkrimen/otto.(*_object).call(0xc82034f860, 0x5, 0x98da20, 0xc82034e7e0, 0xeaaad8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/wiz/go/src/github.com/robertkrimen/otto/type_function.go:161 +0x796
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeCallExpression(0xc82008a480, 0xc8203379e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/wiz/go/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:244 +0x9fc
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeExpression(0xc82008a480, 0x1383150, 0xc8203379e0, 0x0, 0x0, 0x0)
	/Users/wiz/go/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:44 +0x98f
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatement(0xc82008a480, 0x13830b0, 0xc820305eb0, 0x0, 0x0, 0x0)
	/Users/wiz/go/src/github.com/robertkrimen/otto/cmpl_evaluate_statement.go:62 +0x12a8
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatementList(0xc82008a480, 0xc820305e80, 0x1, 0x1, 0x0, 0x0, 0x0)
	/Users/wiz/go/src/github.com/robertkrimen/otto/cmpl_evaluate_statement.go:121 +0xe5
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeProgram(0xc82008a480, 0xc820116460, 0xc821601400, 0x0, 0x0, 0x0)
	/Users/wiz/go/src/github.com/robertkrimen/otto/cmpl_evaluate.go:17 +0x13d
github.com/robertkrimen/otto.(*_runtime).cmpl_runOrEval.func1()
	/Users/wiz/go/src/github.com/robertkrimen/otto/runtime.go:639 +0x3a
github.com/robertkrimen/otto.catchPanic(0xc820343d40, 0x0, 0x0)
	/Users/wiz/go/src/github.com/robertkrimen/otto/error.go:250 +0x5c
github.com/robertkrimen/otto.(*_runtime).cmpl_runOrEval(0xc82008a480, 0x8eb4c0, 0xc8202cbf40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/wiz/go/src/github.com/robertkrimen/otto/runtime.go:640 +0x156
github.com/robertkrimen/otto.(*_runtime).cmpl_run(0xc82008a480, 0x8eb4c0, 0xc8202cbf40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/wiz/go/src/github.com/robertkrimen/otto/runtime.go:651 +0x81
github.com/robertkrimen/otto.Otto.Run(0xc820333020, 0xc82008a480, 0x8eb4c0, 0xc8202cbf40, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/wiz/go/src/github.com/robertkrimen/otto/otto.go:294 +0x6e
github.com/google/cayley/query/gremlin.(*Session).runUnsafe(0xc82005e0e0, 0x8eb4c0, 0xc8202cbf40, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/wiz/go/src/github.com/google/cayley/query/gremlin/session.go:132 +0x23b
github.com/google/cayley/query/gremlin.(*Session).Execute(0xc82005e0e0, 0xc820337770, 0x2c, 0xc820332fc0, 0x64)
	/Users/wiz/go/src/github.com/google/cayley/query/gremlin/session.go:144 +0x369
created by github.com/google/cayley/internal/http.Run
	/Users/wiz/go/src/github.com/google/cayley/internal/http/query.go:52 +0xb4
```

**Comment by dennwc** [comment]
Sure, I recall this bug. Will push fix soon.
