### ISSUE TITLE
Cayley Self-Recovery

### ISSUE THREAD

**Issue by carnalim** [cayleygraph/cayley#450]
So I've noticed that some queries crash Cayley. Cayley panics and goes down and does not have a concept to restart itself. Is there any way to make Cayley recover itself? For instance:

```
Cayley now listening on XXXXX:64210
panic: interface conversion: interface is nil, not string [recovered]
	panic: interface conversion: interface is nil, not string [recovered]
	panic: interface conversion: interface is nil, not string

goroutine 42 [running]:
panic(0xc6ee20, 0xc82038e240)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/cayleygraph/cayley/query/gremlin.(*Session).runUnsafe.func1(0xc82011fea0, 0xc82000abe0)
	/Users/matt/cayley/src/github.com/cayleygraph/cayley/query/gremlin/session.go:100 +0x136
panic(0xc6ee20, 0xc82038e240)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/robertkrimen/otto.catchPanic.func1(0xc820047d50)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/error.go:240 +0x6ff
panic(0xc6ee20, 0xc82038e240)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/cayleygraph/cayley/query/gremlin.argsOf(0xc82007d1e0, 0x0, 0x0, 0x5, 0xd41340, 0xc820375ce0, 0xc8203cea50, 0x2, 0x2, 0xc820248b70, ...)
	/Users/matt/cayley/src/github.com/cayleygraph/cayley/query/gremlin/environ.go:106 +0x6bc
github.com/cayleygraph/cayley/query/gremlin.(*worker).gremlinFunc.func1(0xc82007d1e0, 0x0, 0x0, 0x5, 0xd41340, 0xc820375ce0, 0xc8203cea50, 0x2, 0x2, 0xc820248b70, ...)
	/Users/matt/cayley/src/github.com/cayleygraph/cayley/query/gremlin/traversals.go:61 +0x294
github.com/robertkrimen/otto.(*_object).call(0xc8203cb920, 0x5, 0xd41340, 0xc820375ce0, 0xc8203cea50, 0x2, 0x2, 0x0, 0xc8202555c0, 0x0, ...)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/type_function.go:140 +0x564
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeCallExpression(0xc82007d1e0, 0xc820255950, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:240 +0x9a1
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeExpression(0xc82007d1e0, 0x7f5cc7f23f08, 0xc820255950, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:44 +0x98f
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeDotExpression(0xc82007d1e0, 0xc820255980, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:253 +0x76
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeExpression(0xc82007d1e0, 0x7f5cc7f23d28, 0xc820255980, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:50 +0xc84
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeCallExpression(0xc82007d1e0, 0xc8202559b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:182 +0x8a
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeExpression(0xc82007d1e0, 0x7f5cc7f23f08, 0xc8202559b0, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:44 +0x98f
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeDotExpression(0xc82007d1e0, 0xc8202559e0, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:253 +0x76
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeExpression(0xc82007d1e0, 0x7f5cc7f23d28, 0xc8202559e0, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:50 +0xc84
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeCallExpression(0xc82007d1e0, 0xc820255a10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:182 +0x8a
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeExpression(0xc82007d1e0, 0x7f5cc7f23f08, 0xc820255a10, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:44 +0x98f
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeDotExpression(0xc82007d1e0, 0xc820255a40, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:253 +0x76
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeExpression(0xc82007d1e0, 0x7f5cc7f23d28, 0xc820255a40, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:50 +0xc84
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeCallExpression(0xc82007d1e0, 0xc820255a70, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:182 +0x8a
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeExpression(0xc82007d1e0, 0x7f5cc7f23f08, 0xc820255a70, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:44 +0x98f
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatement(0xc82007d1e0, 0x7f5cc7f23e68, 0xc8204c7550, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/cmpl_evaluate_statement.go:59 +0x1283
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatementList(0xc82007d1e0, 0xc8204c74b0, 0x1, 0x1, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/cmpl_evaluate_statement.go:118 +0xe5
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeProgram(0xc82007d1e0, 0xc8202902a0, 0xc820024d00, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/cmpl_evaluate.go:17 +0x2da
github.com/robertkrimen/otto.(*_runtime).cmpl_run.func1()
	/Users/matt/cayley/src/github.com/robertkrimen/otto/runtime.go:363 +0x37
github.com/robertkrimen/otto.catchPanic(0xc820047da8, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/error.go:243 +0x5c
github.com/robertkrimen/otto.(*_runtime).cmpl_run(0xc82007d1e0, 0xca3580, 0xc820051e00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/runtime.go:364 +0x12b
github.com/robertkrimen/otto.Otto.Run(0xc8204cdce0, 0xc82007d1e0, 0xca3580, 0xc820051e00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/otto.go:292 +0x5c
github.com/cayleygraph/cayley/query/gremlin.(*Session).runUnsafe(0xc82011fea0, 0xca3580, 0xc820051e00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/cayleygraph/cayley/query/gremlin/session.go:132 +0x23b
github.com/cayleygraph/cayley/query/gremlin.(*Session).Execute(0xc82011fea0, 0xc820096000, 0x41c, 0xc8204cdc80, 0x64)
	/Users/matt/cayley/src/github.com/cayleygraph/cayley/query/gremlin/session.go:144 +0x369
created by github.com/cayleygraph/cayley/internal/http.Run
	/Users/matt/cayley/src/github.com/cayleygraph/cayley/internal/http/query.go:52 +0xb4
```

**Comment by carnalim** [comment]
You sure this issue is fixed pulled the most recent code and still got the error:

```
panic: interface conversion: interface is nil, not string [recovered]
	panic: interface conversion: interface is nil, not string [recovered]
	panic: interface conversion: interface is nil, not string

goroutine 38 [running]:
panic(0xc6ee20, 0xc8205292c0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/cayleygraph/cayley/query/gremlin.(*Session).runUnsafe.func1(0xc820360070, 0xc8202f1810)
	/Users/matt/cayley/src/github.com/cayleygraph/cayley/query/gremlin/session.go:100 +0x136
panic(0xc6ee20, 0xc8205292c0)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/robertkrimen/otto.catchPanic.func1(0xc820291d50)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/error.go:240 +0x6ff
panic(0xc6ee20, 0xc8205292c0)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/cayleygraph/cayley/query/gremlin.argsOf(0xc820510000, 0x0, 0x0, 0x5, 0xd41340, 0xc82036db60, 0xc82029c510, 0x2, 0x2, 0xc8203bf220, ...)
	/Users/matt/cayley/src/github.com/cayleygraph/cayley/query/gremlin/environ.go:106 +0x6bc
github.com/cayleygraph/cayley/query/gremlin.(*worker).gremlinFunc.func1(0xc820510000, 0x0, 0x0, 0x5, 0xd41340, 0xc82036db60, 0xc82029c510, 0x2, 0x2, 0xc8203bf220, ...)
	/Users/matt/cayley/src/github.com/cayleygraph/cayley/query/gremlin/traversals.go:61 +0x294
github.com/robertkrimen/otto.(*_object).call(0xc820296c00, 0x5, 0xd41340, 0xc82036db60, 0xc82029c510, 0x2, 0x2, 0x0, 0xc820367da0, 0x0, ...)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/type_function.go:140 +0x564
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeCallExpression(0xc820510000, 0xc820372150, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:240 +0x9a1
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeExpression(0xc820510000, 0x7f934cc20be8, 0xc820372150, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:44 +0x98f
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeDotExpression(0xc820510000, 0xc820372180, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:253 +0x76
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeExpression(0xc820510000, 0x7f934cc20a08, 0xc820372180, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:50 +0xc84
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeCallExpression(0xc820510000, 0xc8203721b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:182 +0x8a
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeExpression(0xc820510000, 0x7f934cc20be8, 0xc8203721b0, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:44 +0x98f
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeDotExpression(0xc820510000, 0xc8203721e0, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:253 +0x76
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeExpression(0xc820510000, 0x7f934cc20a08, 0xc8203721e0, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:50 +0xc84
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeCallExpression(0xc820510000, 0xc820372210, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:182 +0x8a
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeExpression(0xc820510000, 0x7f934cc20be8, 0xc820372210, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:44 +0x98f
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeDotExpression(0xc820510000, 0xc820372240, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:253 +0x76
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeExpression(0xc820510000, 0x7f934cc20a08, 0xc820372240, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:50 +0xc84
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeCallExpression(0xc820510000, 0xc820372270, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:182 +0x8a
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeExpression(0xc820510000, 0x7f934cc20be8, 0xc820372270, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/cmpl_evaluate_expression.go:44 +0x98f
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatement(0xc820510000, 0x7f934cc20b48, 0xc82036ac60, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/cmpl_evaluate_statement.go:59 +0x1283
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatementList(0xc820510000, 0xc82036abc0, 0x1, 0x1, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/cmpl_evaluate_statement.go:118 +0xe5
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeProgram(0xc820510000, 0xc820053c70, 0xc820219d00, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/cmpl_evaluate.go:17 +0x2da
github.com/robertkrimen/otto.(*_runtime).cmpl_run.func1()
	/Users/matt/cayley/src/github.com/robertkrimen/otto/runtime.go:363 +0x37
github.com/robertkrimen/otto.catchPanic(0xc820291da8, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/error.go:243 +0x5c
github.com/robertkrimen/otto.(*_runtime).cmpl_run(0xc820510000, 0xca3580, 0xc820528e40, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/runtime.go:364 +0x12b
github.com/robertkrimen/otto.Otto.Run(0xc82036c240, 0xc820510000, 0xca3580, 0xc820528e40, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/robertkrimen/otto/otto.go:292 +0x5c
github.com/cayleygraph/cayley/query/gremlin.(*Session).runUnsafe(0xc820360070, 0xca3580, 0xc820528e40, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/matt/cayley/src/github.com/cayleygraph/cayley/query/gremlin/session.go:132 +0x23b
github.com/cayleygraph/cayley/query/gremlin.(*Session).Execute(0xc820360070, 0xc820096000, 0x41c, 0xc82036c1e0, 0x64)
	/Users/matt/cayley/src/github.com/cayleygraph/cayley/query/gremlin/session.go:144 +0x369
created by github.com/cayleygraph/cayley/internal/http.Run
	/Users/matt/cayley/src/github.com/cayleygraph/cayley/internal/http/query.go:52 +0xb4
```

**Comment by dennwc** [comment]
Yes, I'm pretty sure you are on d390663bac463e993c06101ac9fdd44741003ba3. Please pull the latest changes and double-check that commit hash matches [HEAD](https://github.com/cayleygraph/cayley/commits/master).
