### ISSUE TITLE
panic: not implemented: need a function from predicates to their associated edges

### ISSUE THREAD

**Issue by steffansluis** [cayleygraph/cayley#543]
Not sure what I did to cause this, but something broke.

```
Process exited with status 2
panic: not implemented: need a function from predicates to their associated edges [recovered]
	panic: Panic at 48: not implemented: need a function from predicates to their associated edges [recovered]

	panic: Panic at 48: not implemented: need a function from predicates to their associated edges
goroutine 42 [running]:
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
panic(0xca4ca0, 0xc420460ba0)
github.com/cayleygraph/cayley/vendor/github.com/dop251/goja.(*Runtime).RunProgram.func1(0xc4200efdc0)
	/go/src/github.com/cayleygraph/cayley/vendor/github.com/dop251/goja/runtime.go:746 +0xa4
panic(0xca4ca0, 0xc420460ba0)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cayleygraph/cayley/vendor/github.com/dop251/goja.(*vm).try.func1(0xc4202c36c0, 0x0, 0xc4200efc98, 0x0, 0x0, 0x0, 0xc4200efcf0)
	/go/src/github.com/cayleygraph/cayley/vendor/github.com/dop251/goja/vm.go:357 +0x400
panic(0xc79b20, 0xc420460b80)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cayleygraph/cayley/graph/path.predicatesMorphism.func1(0xc42045fca8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x30)
	/go/src/github.com/cayleygraph/cayley/graph/path/morphism_apply_functions.go:235 +0x99
github.com/cayleygraph/cayley/graph/path.(*Path).Back(0xc42045fa70, 0xc4202c09ba, 0x5, 0x58af83)
	/go/src/github.com/cayleygraph/cayley/graph/path/path.go:442 +0x145
github.com/cayleygraph/cayley/query/gizmo.(*pathObject).Back(0xc4204685a0, 0xc4202c09ba, 0x5, 0x0)
	/go/src/github.com/cayleygraph/cayley/query/gizmo/traversals.go:124 +0xf7
reflect.callMethod(0xc42045fb90, 0xc4200ef478)
reflect.methodValueCall(0xc4202c09ba, 0x5, 0x0, 0xc420460b70, 0xc4200ef7e8, 0x569758, 0xc42042b0b0, 0xc42045fb90, 0xc420468700, 0x1000000018, ...)
	/usr/local/go/src/reflect/value.go:630 +0x1bb
	/usr/local/go/src/reflect/asm_amd64.s:29 +0x40
reflect.Value.call(0xc96a60, 0xc42045fb90, 0x13, 0xd974fc, 0x4, 0xc4204686e0, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0xc96a60, 0xc42045fb90, 0x13, 0xc4204686e0, 0x1, 0x1, 0xc420460b70, 0x98, 0x0)
	/usr/local/go/src/reflect/value.go:302 +0xa4
github.com/cayleygraph/cayley/vendor/github.com/dop251/goja.(*Runtime).wrapReflectFunc.func1(0x1258f20, 0xc4204685e0, 0xc4202afd60, 0x1, 0x4, 0x0, 0x0)
	/go/src/github.com/cayleygraph/cayley/vendor/github.com/dop251/goja/runtime.go:1004 +0x84a
github.com/cayleygraph/cayley/vendor/github.com/dop251/goja.(*vm)._nativeCall(0xc4202c36c0, 0xc420455e40, 0x1)
	/go/src/github.com/cayleygraph/cayley/vendor/github.com/dop251/goja/vm.go:1820 +0x2d0
github.com/cayleygraph/cayley/vendor/github.com/dop251/goja.call.exec(0xc400000001, 0xc4202c36c0)
	/go/src/github.com/cayleygraph/cayley/vendor/github.com/dop251/goja/vm.go:1801 +0x749
	<autogenerated>:786 +0x5a
github.com/cayleygraph/cayley/vendor/github.com/dop251/goja.(*call).exec(0xc420445efc, 0xc4202c36c0)
github.com/cayleygraph/cayley/vendor/github.com/dop251/goja.(*vm).run(0xc4202c36c0)
	/go/src/github.com/cayleygraph/cayley/vendor/github.com/dop251/goja/vm.go:281 +0x77
github.com/cayleygraph/cayley/vendor/github.com/dop251/goja.(*vm).(github.com/cayleygraph/cayley/vendor/github.com/dop251/goja.run)-fm()
	/go/src/github.com/cayleygraph/cayley/vendor/github.com/dop251/goja/vm.go:368 +0x2a
github.com/cayleygraph/cayley/vendor/github.com/dop251/goja.(*vm).try(0xc4202c36c0, 0xc4200efcf8, 0x0)
	/go/src/github.com/cayleygraph/cayley/vendor/github.com/dop251/goja/vm.go:363 +0x143
github.com/cayleygraph/cayley/vendor/github.com/dop251/goja.(*vm).runTry(0xc4202c36c0, 0xe68220)
	/go/src/github.com/cayleygraph/cayley/vendor/github.com/dop251/goja/vm.go:368 +0x46
	/go/src/github.com/cayleygraph/cayley/vendor/github.com/dop251/goja/runtime.go:757 +0x212
github.com/cayleygraph/cayley/vendor/github.com/dop251/goja.(*Runtime).RunProgram(0xc42039c300, 0xc4202afce0, 0x0, 0x0, 0x0, 0x0)
github.com/cayleygraph/cayley/query/gizmo.(*Session).run(0xc4204400b0, 0xc4202c06e0, 0x15e, 0xc4202af7a0, 0xc4204400b0, 0xc4202afc80, 0x0)
	/go/src/github.com/cayleygraph/cayley/query/gizmo/gizmo.go:217 +0xe9
github.com/cayleygraph/cayley/query/gizmo.(*Session).Execute(0xc4204400b0, 0x7ff51b003040, 0xc4202af7a0, 0xc4202c06e0, 0x15e, 0xc4202afc20, 0x64)
	/go/src/github.com/cayleygraph/cayley/query/gizmo/gizmo.go:240 +0x17d
created by github.com/cayleygraph/cayley/internal/http.(*API).ServeV1Query
	/go/src/github.com/cayleygraph/cayley/internal/http/query.go:115 +0x3a8
```

**Comment by dennwc** [comment]
@steffansluis Thanks for reporting this, but it's not really a bug, rather a TODO. It will happen if you try to use Predicates() and then go in reverse (or use Back).

Do you have a real use case for this?

**Comment by dennwc** [comment]
I will assume that this was done accidentally and there is no real use case for such query. Reopen if I'm wrong.
