### ISSUE TITLE
 could not parse config file "./cayley.yml": invalid character 's' looking for beginning of value

### ISSUE THREAD

**Issue by Fei-Guang** [cayleygraph/cayley#564]
**Description**

**Steps to reproduce the issue:**
1.   ~/downloads/cayley_v0.6.0_linux_amd64$ ./cayley init --config ./cayley.yml
2.   cat ./cayley.yml
```
store:
  # backend to use
  backend: sql
  # address or path for the database
  address: "mysql://root:gld@db:3306/cayley?sslmode=disable"
  # open database in read-only mode
  read_only: false
  # backend-specific options
  options:
    nosync: false
```
  

**Received results:**

```
F0418 12:49:01.600949   20236 cayley.go:119] could not parse config file "./cayley.yml": invalid character 's' looking for beginning of value
goroutine 1 [running]:
github.com/cayleygraph/cayley/vendor/github.com/golang/glog.stacks(0xf12500, 0xc400000000, 0x8e, 0xad)
        /home/barak/src/cayley/src/github.com/cayleygraph/cayley/vendor/github.com/golang/glog/glog.go:769 +0xa5
github.com/cayleygraph/cayley/vendor/github.com/golang/glog.(*loggingT).output(0xef5440, 0xc400000003, 0xc420090180, 0xec1dd1, 0x9, 0x77, 0x0)
        /home/barak/src/cayley/src/github.com/cayleygraph/cayley/vendor/github.com/golang/glog/glog.go:720 +0x357
github.com/cayleygraph/cayley/vendor/github.com/golang/glog.(*loggingT).printDepth(0xef5440, 0xc400000003, 0x3, 0xc4200efb88, 0x1, 0x1)
        /home/barak/src/cayley/src/github.com/cayleygraph/cayley/vendor/github.com/golang/glog/glog.go:646 +0x126
github.com/cayleygraph/cayley/vendor/github.com/golang/glog.FatalDepth(0x3, 0xc4200efb88, 0x1, 0x1)
        /home/barak/src/cayley/src/github.com/cayleygraph/cayley/vendor/github.com/golang/glog/glog.go:1134 +0x5d
github.com/cayleygraph/cayley/clog/glog.Logger.Fatalf(0xb4163b, 0x2, 0xc420186b40, 0x1, 0x1)
        /home/barak/src/cayley/src/github.com/cayleygraph/cayley/clog/glog/glog.go:25 +0xe3
github.com/cayleygraph/cayley/clog/glog.(*Logger).Fatalf(0xf12790, 0xb4163b, 0x2, 0xc420186b40, 0x1, 0x1)
        <autogenerated>:4 +0x7e
github.com/cayleygraph/cayley/clog.Fatalf(0xb4163b, 0x2, 0xc420186b40, 0x1, 0x1)
        /home/barak/src/cayley/src/github.com/cayleygraph/cayley/clog/clog.go:65 +0x76
main.configFrom(0x7ffe4a9df566, 0xc, 0x0)
        /home/barak/src/cayley/src/github.com/cayleygraph/cayley/cmd/cayley/cayley.go:119 +0x301
main.main()
        /home/barak/src/cayley/src/github.com/cayleygraph/cayley/cmd/cayley/cayley.go:182 +0x207

```

**Expected results:**

**Output of `cayley version` or commit hash:**

```
Cayley v0.6.0 built 2016-09-27T14:21:17-07:00
```

**Environment details:**

Backend database: `(database and version)`

**Comment by dennwc** [comment]
What version of Cayley are you using? If it's v0.6, as directory name suggests, you should use docs from [v0.6.0](https://github.com/cayleygraph/cayley/tree/v0.6.0) branch. Only v0.7 (master) branch supports yaml configs.

**Comment by Fei-Guang** [comment]
json woks on 0.6.0
