### ISSUE TITLE
runtime error: index out of range

### ISSUE THREAD

**Issue by h4ck3rm1k3** [cayleygraph/cayley#593]
# data
https://gist.github.com/h4ck3rm1k3/a81776f6ac56eb4af82d25f01c9f42a2#file-tree-dump-c-001t-tu-nq2-bz2

# Query
```
nm =    g.Morphism().In("op_1").Tag("op1" ).Out("nodetype").Tag("NT_op1").Back("op1") 
 .Union(g.Morphism().In("op_0").Tag("op0" ).Has("nodetype","eq_expr").Out("nodetype").Tag("NT_eq_op0").Back("op0"))
 .Union(g.Morphism().In("op_0").Tag("op0" ).Has("nodetype","cond_expr").Out("nodetype").Tag("NT_cond_op0").Back("op0"))
 .Union(g.Morphism().In("op_2").Tag("op2" ).Out("nodetype").Tag("Nt_op2").Back("op2"))  
 .Union(g.Morphism().In("body").Tag("body" ).Has("nodetype","bind_expr").Out("nodetype").Tag("Nt_bind").Back("body"))
 .Union(g.Morphism().In("body").Tag("body2" ).Has("nodetype","switch_expr").Out("nodetype").Tag("Nt_switch").Back("body2"))
 .Union(g.Morphism().In([],"somenm").Tag("num" ).Has("nodetype","statement_list").Out("nodetype").Tag("Nt_sl").Back("num"))

n1 =    g.Morphism().In([],"fld").Tag("op1" ).Out("nodetype").Tag("NT_op1").Back("op1") 
g.V("field_decl").In("nodetype","nt1").Tag("field").
Out("scpe").Out("name","n1").Out("name","n2").Has("strg","tree_base").Tag("struct_name")
.Back("field").Out("name","n3").Has("strg","code").Tag("code").Back("field").In("op_1","op1").Has("nodetype","component_ref").Tag("00_op1_cr1")  

//.Follow(nm)
.FollowRecursive(n1)
.In("body","body").Has("nodetype","function_decl").Tag("decl")
//.Back("decl").Out("name","n1").Out("strg","stg").Tag("name")
//.Back('decl').Out(["srcp"],"srcp").Tag("SourceFileLine")
.All()
```

# Error 
```
make -k test
GOPATH=/home/mdupont/gocode ./cayley http  --host 0.0.0.0:64210 -i ~/experiments/gcc-1/build/gcc/tree-dump.c.001t.tu.pq
panic: runtime error: index out of range [recovered]
	panic: Panic at 336: runtime error: index out of range [recovered]
	panic: Panic at 336: runtime error: index out of range

goroutine 30 [running]:
panic(0xcbd4a0, 0xc42f7025f0)
	/usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1
github.com/cayleygraph/cayley/vendor/github.com/dop251/goja.(*Runtime).RunProgram.func1(0xc433591db0)
	/home/mdupont/gocode/src/github.com/cayleygraph/cayley/vendor/github.com/dop251/goja/runtime.go:746 +0xa4
panic(0xcbd4a0, 0xc42f7025f0)
	/usr/lib/go-1.7/src/runtime/panic.go:458 +0x243
github.com/cayleygraph/cayley/vendor/github.com/dop251/goja.(*vm).try.func1(0xc4381889c0, 0x0, 0xc433591c88, 0x0, 0x0, 0x0, 0xc433591ce0)
	/home/mdupont/gocode/src/github.com/cayleygraph/cayley/vendor/github.com/dop251/goja/vm.go:357 +0x400
panic(0xcd4140, 0xc420010140)
	/usr/lib/go-1.7/src/runtime/panic.go:458 +0x243
github.com/cayleygraph/cayley/graph/iterator.(*Recursive).TagResults(0xc438dcd040, 0xc4240e2030)
	/home/mdupont/gocode/src/github.com/cayleygraph/cayley/graph/iterator/recursive.go:99 +0x590
github.com/cayleygraph/cayley/graph/iterator.(*LinksTo).TagResults(0xc4389ac900, 0xc4240e2030)
	/home/mdupont/gocode/src/github.com/cayleygraph/cayley/graph/iterator/linksto.go:99 +0x1d0
github.com/cayleygraph/cayley/graph/iterator.(*Materialize).TagResults(0xc4389ac9c0, 0xc4240e2030)
	/home/mdupont/gocode/src/github.com/cayleygraph/cayley/graph/iterator/materialize.go:81 +0x74
github.com/cayleygraph/cayley/graph/iterator.(*And).TagResults(0xc438f4f6c0, 0xc4240e2030)
	/home/mdupont/gocode/src/github.com/cayleygraph/cayley/graph/iterator/and.go:84 +0x20c
github.com/cayleygraph/cayley/graph/iterator.(*HasA).TagResults(0xc4389ad380, 0xc4240e2030)
	/home/mdupont/gocode/src/github.com/cayleygraph/cayley/graph/iterator/hasa.go:129 +0x1d0
github.com/cayleygraph/cayley/graph/iterator.(*And).TagResults(0xc4384ee620, 0xc4240e2030)
	/home/mdupont/gocode/src/github.com/cayleygraph/cayley/graph/iterator/and.go:81 +0x264
github.com/cayleygraph/cayley/graph.(*IterateChain).TagEach(0xc433591280, 0xc433591250, 0x0, 0x0)
	/home/mdupont/gocode/src/github.com/cayleygraph/cayley/graph/iterate.go:236 +0x12a
github.com/cayleygraph/cayley/query/gizmo.(*Session).runIterator(0xc42e464d10, 0x1231760, 0xc439c48380, 0x0, 0x0)
	/home/mdupont/gocode/src/github.com/cayleygraph/cayley/query/gizmo/gizmo.go:199 +0x1f2
github.com/cayleygraph/cayley/query/gizmo.(*pathObject).GetLimit(0xc439f6b3c0, 0xffffffffffffffff, 0x5b301e, 0xc42d1fa960)
	/home/mdupont/gocode/src/github.com/cayleygraph/cayley/query/gizmo/finals.go:31 +0xdc
github.com/cayleygraph/cayley/query/gizmo.(*pathObject).All(0xc439f6b3c0, 0x0, 0x0)
	/home/mdupont/gocode/src/github.com/cayleygraph/cayley/query/gizmo/finals.go:36 +0x34
reflect.callMethod(0xc43a4d1dd0, 0xc433591468)
	/usr/lib/go-1.7/src/reflect/value.go:630 +0x1bb
reflect.methodValueCall(0x0, 0x0, 0xc433721950, 0xc42fc58a00, 0xc4335917d8, 0x57d518, 0xc433721950, 0xc43a4d1dd0, 0xc42fc58a00, 0x10, ...)
	/usr/lib/go-1.7/src/reflect/asm_amd64.s:29 +0x40
reflect.Value.call(0xc8a380, 0xc43a4d1dd0, 0x13, 0xdb89bf, 0x4, 0x13bf680, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/lib/go-1.7/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0xc8a380, 0xc43a4d1dd0, 0x13, 0x13bf680, 0x0, 0x0, 0xc434034300, 0xc43a4d1e00, 0x0)
	/usr/lib/go-1.7/src/reflect/value.go:302 +0xa4
github.com/cayleygraph/cayley/vendor/github.com/dop251/goja.(*Runtime).wrapReflectFunc.func1(0x1230ac0, 0xc439f6b420, 0xc4271c0320, 0x0, 0x4, 0x0, 0x0)
	/home/mdupont/gocode/src/github.com/cayleygraph/cayley/vendor/github.com/dop251/goja/runtime.go:1004 +0x84a
github.com/cayleygraph/cayley/vendor/github.com/dop251/goja.(*vm)._nativeCall(0xc4381889c0, 0xc43a3338c0, 0x0)
	/home/mdupont/gocode/src/github.com/cayleygraph/cayley/vendor/github.com/dop251/goja/vm.go:1820 +0x2d0
github.com/cayleygraph/cayley/vendor/github.com/dop251/goja.call.exec(0xc400000000, 0xc4381889c0)
	/home/mdupont/gocode/src/github.com/cayleygraph/cayley/vendor/github.com/dop251/goja/vm.go:1801 +0x749
github.com/cayleygraph/cayley/vendor/github.com/dop251/goja.(*call).exec(0xc42fcc8ca8, 0xc4381889c0)
	<autogenerated>:786 +0x5a
github.com/cayleygraph/cayley/vendor/github.com/dop251/goja.(*vm).run(0xc4381889c0)
	/home/mdupont/gocode/src/github.com/cayleygraph/cayley/vendor/github.com/dop251/goja/vm.go:281 +0x77
github.com/cayleygraph/cayley/vendor/github.com/dop251/goja.(*vm).(github.com/cayleygraph/cayley/vendor/github.com/dop251/goja.run)-fm()
	/home/mdupont/gocode/src/github.com/cayleygraph/cayley/vendor/github.com/dop251/goja/vm.go:368 +0x2a
github.com/cayleygraph/cayley/vendor/github.com/dop251/goja.(*vm).try(0xc4381889c0, 0xc433591ce8, 0x0)
	/home/mdupont/gocode/src/github.com/cayleygraph/cayley/vendor/github.com/dop251/goja/vm.go:363 +0x143
github.com/cayleygraph/cayley/vendor/github.com/dop251/goja.(*vm).runTry(0xc4381889c0, 0xe3fb78)
	/home/mdupont/gocode/src/github.com/cayleygraph/cayley/vendor/github.com/dop251/goja/vm.go:368 +0x46
github.com/cayleygraph/cayley/vendor/github.com/dop251/goja.(*Runtime).RunProgram(0xc434034300, 0xc42e413500, 0x0, 0x0, 0x0, 0x0)
	/home/mdupont/gocode/src/github.com/cayleygraph/cayley/vendor/github.com/dop251/goja/runtime.go:757 +0x212
github.com/cayleygraph/cayley/query/gizmo.(*Session).run(0xc42e464d10, 0xc4488ea100, 0x569, 0xc42e412fc0, 0xc42e464d10, 0xc42e4134a0, 0x0)
	/home/mdupont/gocode/src/github.com/cayleygraph/cayley/query/gizmo/gizmo.go:239 +0xe9
github.com/cayleygraph/cayley/query/gizmo.(*Session).Execute(0xc42e464d10, 0x7fab9f0d41b0, 0xc42e412fc0, 0xc4488ea100, 0x569, 0xc42e413440, 0x64)
	/home/mdupont/gocode/src/github.com/cayleygraph/cayley/query/gizmo/gizmo.go:262 +0x17d
created by github.com/cayleygraph/cayley/internal/http.(*API).ServeV1Query
	/home/mdupont/gocode/src/github.com/cayleygraph/cayley/internal/http/query.go:117 +0x3a5
Makefile:2: recipe for target 'test' failed
make: *** [test] Error 2

Compilation exited abnormally with code 2 at Sat May 13 17:51:53
```

# revision 
on master/head
commit 61125879b57ebd2277876ed95fffd244fc4bf8df
Date:   Fri May 12 23:19:55 2017 +0300

**Comment by h4ck3rm1k3** [comment]
adding  ".Out("srcp")"  to this causes the crash
```
nts = g.Morphism().Has("nodetype","eq_expr")
.Union( g.Morphism().Has("nodetype","cond_expr"))
.Union( g.Morphism().Has("nodetype","statement_list"))
.Union( g.Morphism().Has("nodetype","bind_expr"))
.Union( g.Morphism().Has("nodetype","switch_expr"))
.Union( g.Morphism().Has("nodetype","statement_list"))

//nm =    g.Morphism().In([],"rel").Tag("op1").Out("nodetype").Tag("NT_op1").Back("op1");
nm =    g.Morphism().In(["op_0","op_1"],"rel").Tag("op1").Has("nodetype","eq_expr").Out("nodetype").Tag("NT_op").Back("op1")
.Union( g.Morphism().In(["op_0"],"rel").Tag("op2").Has("nodetype","cond_expr").Out("nodetype").Tag("NT_op").Back("op2"))
.Union( g.Morphism().In([  "0",  "1",  "10",  "100",  "101", "102",  "103",  "104",
  "105",  "106",  "107",  "108",   "109",  "11",   "110",  "111",   "112",  "113",  "114",  "115",  "116",  "117",   "118",  "119",  "12",  "120",  "121",  "122",  "123",  "124",  "125",  "126",  "127",  "128",  "129",  "13",  "130",  "131",  "132",  "133",  "134",  "135",  "136",  "137",  "138",  "139",  "14",  "140",  "141",  "142",  "143",  "144",  "145",  "146",  "147",  "148",  "149",  "15",  "150",  "151",  "152",  "153", "154",  "155",  "156",  "157",  "158",  "159",  "16",  "160",  "161",  "162",  "163",  "164",  "165",  "166",  "167",  "168",  "169",  "17",  "170",  "171",  "172",  "173",  "174",  "175",  "176",  "177",  "178",  "179",  "18",  "180",  "181",  "182",  "183",  "184",  "185",  "186",  "187",  "188",  "189",  "19",  "190", "191",  "192",  "193",  "194",  "195",  "196",  "197",  "198",  "199",  "2",  "20",  "200",  "201",  "202",  "203",  "204",  "205",  "206",  "207",  "208",  "209",  "21",  "210",  "211",  "212",  "213",  "214",  "215",  "22",  "23",  "24",  "25",  "26",  "27",  "28",  "29",  "3",  "30",  "31",  "32",  "33",  "34",  "35",  "36",  "37",  "38",  "39",  "4",  "40",  "41",  "42",  "43",  "44",  "45",  "46",  "47",  "48",  "49",  "5",  "50",  "51",  "52",  "53",  "54",  "55",  "56",  "57",  "58",  "59",  "6",  "60",  "61",  "62",  "63",  "64",  "65",  "66",  "67",  "68",  "69",  "7",  "70",  "71",  "72",  "73",  "74",  "75",  "76",  "77",  "78",  "79",  "8",  "80",  "81",  "82",  "83",  "84",  "85",  "86",  "87",  "88",  "89",  "9",  "90",  "91",  "92",  "93",  "94",  "95",  "96",  "97",  "98", "99"
  ]  ,"rel").Tag("op3").Has("nodetype","statement_list").Out("nodetype").Tag("NT_op").Back("op3"))
.Union( g.Morphism().In(["body"],"rel").Tag("op4").Has("nodetype","bind_expr").Out("nodetype").Tag("NT_op").Back("op4"))
.Union( g.Morphism().In(["body"],"rel").Tag("op5").Has("nodetype","switch_expr").Out("nodetype").Tag("NT_op").Back("op5"));

nm2 =    g.Morphism().In("op_0","op_0_nop_expr").Tag("op1").Has("nodetype","nop_expr").Out("nodetype").Back("op1")

nm3 =    g.Morphism().In("op_0","rel").Tag("op1").Has("nodetype","nop_expr").Out("nodetype").Tag("nt1").Back("op1")

n1 = g.Morphism().In("op_0","fldop_0").Tag("NT_inop").Has("node_type","eq_expr").Out("nodetype").Tag("NT1").Back("NT_inop");

start = g.Morphism().Has("nodetype","field_decl").Tag("field").
    Out("scpe").Out("name").Out("name").Has("strg","tree_base").Back("field").
    Out("name").Has("strg","code").Back("field").
    In("op_1").Has("nodetype","component_ref").Tag("00_op1_cr1")

finish = g.Morphism().In("body").Has("nodetype","function_decl").Tag("decl")
	//.Back("decl")
	.Out("name").Out("strg").Tag("name")
	.Back('decl').Out("srcp")
//.Tag("sourcefile")

function foo(x) {
	alert(x);
}

g.V()
.Follow(start)
.FollowRecursive(nm)

.Follow(finish)
    .All();
    
```

**Comment by h4ck3rm1k3** [comment]
Running this query  does not crash, but returns null.
if you first uncomment //.FollowRecursive(nm) and run it, and then comment it out and run it, it crashes!
```
nts = g.Morphism().Has("nodetype","eq_expr")
.Union( g.Morphism().Has("nodetype","cond_expr"))
.Union( g.Morphism().Has("nodetype","statement_list"))
.Union( g.Morphism().Has("nodetype","bind_expr"))
.Union( g.Morphism().Has("nodetype","switch_expr"))
.Union( g.Morphism().Has("nodetype","statement_list"))

//nm =    g.Morphism().In([],"rel").Tag("op1").Out("nodetype").Tag("NT_op1").Back("op1");
nm =    g.Morphism().In(["op_0","op_1"],"rel").Tag("op1").Has("nodetype","eq_expr").Out("nodetype").Tag("NT_op").Back("op1")
.Union( g.Morphism().In(["op_0"],"rel").Tag("op2").Has("nodetype","cond_expr").Out("nodetype").Tag("NT_op").Back("op2"))
.Union( g.Morphism().In([  "0",  "1",  "10",  "100",  "101", "102",  "103",  "104",
  "105",  "106",  "107",  "108",   "109",  "11",   "110",  "111",   "112",  "113",  "114",  "115",  "116",  "117",   "118",  "119",  "12",  "120",  "121",  "122",  "123",  "124",  "125",  "126",  "127",  "128",  "129",  "13",  "130",  "131",  "132",  "133",  "134",  "135",  "136",  "137",  "138",  "139",  "14",  "140",  "141",  "142",  "143",  "144",  "145",  "146",  "147",  "148",  "149",  "15",  "150",  "151",  "152",  "153", "154",  "155",  "156",  "157",  "158",  "159",  "16",  "160",  "161",  "162",  "163",  "164",  "165",  "166",  "167",  "168",  "169",  "17",  "170",  "171",  "172",  "173",  "174",  "175",  "176",  "177",  "178",  "179",  "18",  "180",  "181",  "182",  "183",  "184",  "185",  "186",  "187",  "188",  "189",  "19",  "190", "191",  "192",  "193",  "194",  "195",  "196",  "197",  "198",  "199",  "2",  "20",  "200",  "201",  "202",  "203",  "204",  "205",  "206",  "207",  "208",  "209",  "21",  "210",  "211",  "212",  "213",  "214",  "215",  "22",  "23",  "24",  "25",  "26",  "27",  "28",  "29",  "3",  "30",  "31",  "32",  "33",  "34",  "35",  "36",  "37",  "38",  "39",  "4",  "40",  "41",  "42",  "43",  "44",  "45",  "46",  "47",  "48",  "49",  "5",  "50",  "51",  "52",  "53",  "54",  "55",  "56",  "57",  "58",  "59",  "6",  "60",  "61",  "62",  "63",  "64",  "65",  "66",  "67",  "68",  "69",  "7",  "70",  "71",  "72",  "73",  "74",  "75",  "76",  "77",  "78",  "79",  "8",  "80",  "81",  "82",  "83",  "84",  "85",  "86",  "87",  "88",  "89",  "9",  "90",  "91",  "92",  "93",  "94",  "95",  "96",  "97",  "98", "99"
  ]  ,"rel").Tag("op3").Has("nodetype","statement_list").Out("nodetype").Tag("NT_op").Back("op3"))
.Union( g.Morphism().In(["body"],"rel").Tag("op4").Has("nodetype","bind_expr").Out("nodetype").Tag("NT_op").Back("op4"))
.Union( g.Morphism().In(["body"],"rel").Tag("op5").Has("nodetype","switch_expr").Out("nodetype").Tag("NT_op").Back("op5"));

nm2 =    g.Morphism().In("op_0","op_0_nop_expr").Tag("op1").Has("nodetype","nop_expr").Out("nodetype").Back("op1")

nm3 =    g.Morphism().In("op_0","rel").Tag("op1").Has("nodetype","nop_expr").Out("nodetype").Tag("nt1").Back("op1")

n1 = g.Morphism().In("op_0","fldop_0").Tag("NT_inop").Has("node_type","eq_expr").Out("nodetype").Tag("NT1").Back("NT_inop");

start = g.Morphism().Has("nodetype","field_decl").Tag("field").
    Out("scpe").Out("name").Out("name").Has("strg","tree_base").Back("field").
    Out("name").Has("strg","code").Back("field").
    In("op_1").Has("nodetype","component_ref").Tag("00_op1_cr1")

finish = g.Morphism().In("body").Has("nodetype","function_decl").Tag("decl")
	//.Back("decl")
	.Out("name").Out("strg").Tag("name")
	

g.V()
.Follow(start)
//.FollowRecursive(nm)
.Follow(finish)
    .All();
    
```

**Comment by dennwc** [comment]
Reproduced locally. Thanks for tracking this!

**Comment by h4ck3rm1k3** [comment]
Yes, it appears to be fixed.
