### ISSUE TITLE
Crash in repl debug

### ISSUE THREAD

**Issue by h4ck3rm1k3** [cayleygraph/cayley#599]
```
cayley> :debug
Error: cannot parse "" as a valid boolean - acceptable values: 't'|'true' or 'f'|'false'
cayley> :debug t
panic: unexposed in glog

goroutine 1 [running]:
panic(0xc8f900, 0xc43cb9e040)
	/usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1
github.com/cayleygraph/cayley/clog/glog.Logger.SetV(0x2)
	/home/mdupont/gocode/src/github.com/cayleygraph/cayley/clog/glog/glog.go:34 +0x6d
github.com/cayleygraph/cayley/clog/glog.(*Logger).SetV(0x13bf680, 0x2)
	<autogenerated>:6 +0x56
github.com/cayleygraph/cayley/clog.SetV(0x2)
	/home/mdupont/gocode/src/github.com/cayleygraph/cayley/clog/clog.go:50 +0x4e
github.com/cayleygraph/cayley/internal/db.Repl(0x7fa4f2cdc040, 0xc43cbaa2c0, 0xc4201ff2c0, 0xdba1b4, 0x5, 0x6fc23ac00, 0x0, 0x0)
	/home/mdupont/gocode/src/github.com/cayleygraph/cayley/internal/db/repl.go:158 +0xc83
github.com/cayleygraph/cayley/cmd/cayley/command.NewReplCmd.func1(0xc420171b00, 0xc4201fee00, 0x0, 0x2, 0x0, 0x0)
	/home/mdupont/gocode/src/github.com/cayleygraph/cayley/cmd/cayley/command/repl.go:91 +0x207
github.com/spf13/cobra.(*Command).execute(0xc420171b00, 0xc4201fedc0, 0x2, 0x2, 0xc420171b00, 0xc4201fedc0)
	/home/mdupont/gocode/src/github.com/spf13/cobra/command.go:656 +0x247
github.com/spf13/cobra.(*Command).ExecuteC(0x1397fe0, 0x0, 0xc420094a50, 0x1398200)
	/home/mdupont/gocode/src/github.com/spf13/cobra/command.go:735 +0x367
github.com/spf13/cobra.(*Command).Execute(0x1397fe0, 0x0, 0x0)
	/home/mdupont/gocode/src/github.com/spf13/cobra/command.go:694 +0x2b
main.main()
	/home/mdupont/gocode/src/github.com/cayleygraph/cayley/cmd/cayley/cayley.go:191 +0x31
Makefile:14: recipe for target 'repl' failed
make: *** [repl] Error 2

Comint exited abnormally with code 2 at Sun May 14 15:20:51
```

**Comment by dennwc** [comment]
Please use `cayley repl -v 10 ...` for debug. I'll fix an error message here.
