### ISSUE TITLE
error while directly hitting the API in cayley

### ISSUE THREAD

**Issue by irfan14** [cayleygraph/cayley#604]
when I am trying to hit the API directly to load the data into the cayley, I am getting an exception called java.net.BindException. I have enclosed the error that I am getting in my console. i have added a timeout of 30 seconds when i am handling bulk data. can this be one without adding timeout in my code..????
```
java.net.BindException: Address already in use: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:72)
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:118)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:357)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:218)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:194)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at com.cts.cayley.process.JSONConnection1.executeArray(JSONConnection1.java:41)
	at com.cts.cayley.DAO.Connector.formQuery(Connector.java:480)
	at com.cts.cayley.DAO.RDBConnector.getData(RDBConnector.java:68)
	at com.cts.cayley.process.CayleyConverter.main(CayleyConverter.java:66)
```

**Comment by dennwc** [comment]
I don't think it's related to Cayley in any way. The exception is `java.net.BindException: Address already in use: connect` meaning Java failed to bind a port for the connection.
