### ISSUE TITLE
LoadPathTo panics with bolt backend

### ISSUE THREAD

**Issue by ferdicar** [cayleygraph/cayley#759]
**Description**

Loading path to structure panics when an identifier is referred multiple times by the same object

**Steps to reproduce the issue:**

The following code demostrate the issue:

```go
// Wrapper ...
type Wrapper struct {
	rdfType struct{} `quad:"@type > Wrapper"`
	ID      quad.IRI `quad:"@id"`
	Child1  Item     `quad:"child1"`
	Child2  Item     `quad:"child2"`
}

// Item ...
type Item struct {
	rdfType struct{} `quad:"@type > Item"`
	ID      quad.IRI `quad:"@id"`
	Title   string   `quad:"title,optional"`
}

func main() {
	var err error
	err = graph.InitQuadStore("bolt", "build/store", nil)

	if err != nil {
		log.Fatal(err)
	}

	s, err := cayley.NewGraph("bolt", "build/store", nil)
	qw := graph.NewWriter(s)
	schema := schema.NewConfig()

	w := Wrapper{
		ID: quad.IRI("w1"),
		Child1: Item{
			ID: quad.IRI("c1"),
		},
		Child2: Item{
			ID: quad.IRI("c1"),
		},
	}

	log.Println("writing quads")
	_, err = schema.WriteAsQuads(qw, w)
	if err != nil {
		log.Println("error writing quad", err)
	}
	log.Println("flushing quads")
	err = qw.Flush()
	if err != nil {
		log.Println("error flushing quad data", err)
	}

	pa := path.StartPath(s.QuadStore).Is(w.ID)

	wrapper := Wrapper{}
	log.Println("reading data")
	err = schema.LoadPathTo(context.Background(), s.QuadStore, &wrapper, pa)
	if err != nil {
		log.Fatal("error reading path: ", err)
	}

	if !reflect.DeepEqual(w, wrapper) {
		log.Fatal("not match")
	}
	log.Println("written and read data match")
```

**Received results:**

```
2019/01/07 10:21:23 writing quads
2019/01/07 10:21:23 flushing quads
2019/01/07 10:21:23 reading data
panic: reflect.Set: value of type *main.Item is not assignable to type main.Item

goroutine 1 [running]:
reflect.Value.assignTo(0x1250c80, 0xc0000d0800, 0x16, 0x12c7816, 0xb, 0x1294c00, 0x0, 0x1, 0x150a6c0, 0xc0000b0c60)
	/usr/local/Cellar/go/1.11/libexec/src/reflect/value.go:2239 +0x44c
reflect.Value.Set(0x1294c00, 0xc004b4e0e0, 0x199, 0x1250c80, 0xc0000d0800, 0x16)
	/usr/local/Cellar/go/1.11/libexec/src/reflect/value.go:1373 +0xa7
github.schibsted.io/spt-DevRel/go-ragtag/vendor/github.com/cayleygraph/cayley/schema.(*loader).loadIteratorToDepth(0xc004b4bb90, 0x130a120, 0xc000063c80, 0x1294c00, 0xc004b4e0e0, 0x199, 0xfffffffffffffffe, 0x130bb00, 0xc004b3acc0, 0x0, ...)
	.../vendor/github.com/cayleygraph/cayley/schema/loader.go:442 +0xbe1
github.schibsted.io/spt-DevRel/go-ragtag/vendor/github.com/cayleygraph/cayley/schema.(*loader).loadToValue(0xc004b4bb90, 0x130a120, 0xc000062ab0, 0x129fe60, 0xc004b42190, 0x199, 0xffffffffffffffff, 0xc000062d20, 0x0, 0x0, ...)
	.../vendor/github.com/cayleygraph/cayley/schema/loader.go:345 +0x88e
github.schibsted.io/spt-DevRel/go-ragtag/vendor/github.com/cayleygraph/cayley/schema.(*loader).loadIteratorToDepth(0xc004b4bb90, 0x130a120, 0xc000062ab0, 0x1250cc0, 0xc004b42190, 0x16, 0xffffffffffffffff, 0x130bb00, 0xc004b3a480, 0x0, ...)
	.../vendor/github.com/cayleygraph/cayley/schema/loader.go:480 +0x7cc
github.schibsted.io/spt-DevRel/go-ragtag/vendor/github.com/cayleygraph/cayley/schema.(*Config).LoadIteratorToDepth(0xc00004b500, 0x130a0e0, 0xc000016070, 0x130b440, 0xc00007c1e0, 0x1250cc0, 0xc004b42190, 0x16, 0xffffffffffffffff, 0x130bb00, ...)
	.../vendor/github.com/cayleygraph/cayley/schema/loader.go:142 +0x133
github.schibsted.io/spt-DevRel/go-ragtag/vendor/github.com/cayleygraph/cayley/schema.(*Config).LoadIteratorTo(0xc00004b500, 0x130a0e0, 0xc000016070, 0x130b440, 0xc00007c1e0, 0x1250cc0, 0xc004b42190, 0x16, 0x130bb00, 0xc004b3a480, ...)
	.../vendor/github.com/cayleygraph/cayley/schema/loader.go:131 +0xad
github.schibsted.io/spt-DevRel/go-ragtag/vendor/github.com/cayleygraph/cayley/schema.(*Config).LoadPathTo(0xc00004b500, 0x130a0e0, 0xc000016070, 0x130b440, 0xc00007c1e0, 0x1250cc0, 0xc004b42190, 0xc0000680c0, 0x0, 0xc000018360)
	.../vendor/github.com/cayleygraph/cayley/schema/loader.go:121 +0x145
main.main()
	.../main.go:82 +0x5d5
exit status 2
```

Data is correctly stored and can be read using REPL

**Expected results:**

Should correctly fetch data and store in the structure.

**Output of `cayley version` or commit hash:**

```
Cayley version: 0.7.5
Git commit hash: 6ce5dd09d00aff6942ff0f059366659123b18e41
Build date: 2018-11-26T18:11:14Z
```

**Environment details:**

Using `bolt` backend the code panic while with postgres fails more gracefullly be reporting a "not found" error.  No other backends have been tested.

**Comment by dennis10001** [comment]
759

**Comment by dennis10001** [comment]
759
