### ISSUE TITLE
Cayley panics on a single specific query (GraphQL)

### ISSUE THREAD

**Issue by Jessev6** [cayleygraph/cayley#806]
**Description**
Quering through the GraphQL API for extended data (multiple levels deep with reversed relationship lookups) causes a panic and does not return any data. Other queries return correct data, and do not cause crashes.

**Steps to reproduce the issue:**
1. Currently unknown cause
2. Query for data using the graphql v2 api

**Received results:**

None

```
I0808 07:08:49.793106       1 http.go:89] started POST /api/v1/query/graphql for 127.0.0.1:49774
2019/08/08 07:08:49 http: panic serving 127.0.0.1:49774: runtime error: invalid memory address or nil pointer dereference
goroutine 1285 [running]:
net/http.(*conn).serve.func1(0xc424f06140)
	/usr/local/go/src/net/http/server.go:1726 +0xd0
panic(0xf802e0, 0x199a400)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/cayleygraph/cayley/graph/kv.(*QuadStore).ValuesOf(0xc420251040, 0x11b6ae0, 0xc425e9f620, 0xc4257dd3d0, 0x1, 0x1, 0xffffffffffffffff, 0x0, 0x1, 0xc42663b928, ...)
	/go/src/github.com/cayleygraph/cayley/graph/kv/quadstore.go:263 +0x562
github.com/cayleygraph/cayley/graph.ValuesOf(0x11b6ae0, 0xc425e9f620, 0x11bcec0, 0xc420251040, 0xc4257dd3d0, 0x1, 0x1, 0xc4257dd3e0, 0x1, 0x1, ...)
	/go/src/github.com/cayleygraph/cayley/graph/quadstore.go:40 +0x1f3
github.com/cayleygraph/cayley/query/graphql.iterateObject(0x11b6ae0, 0xc425e9f620, 0x11bcec0, 0xc420251040, 0xc4257ee300, 0xc425cd6980, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cayleygraph/cayley/query/graphql/graphql.go:303 +0x1924
github.com/cayleygraph/cayley/query/graphql.iterateObject(0x11b6ae0, 0xc425e9f620, 0x11bcec0, 0xc420251040, 0xc42586f680, 0xc4255776c0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cayleygraph/cayley/query/graphql/graphql.go:343 +0x1db6
github.com/cayleygraph/cayley/query/graphql.iterateObject(0x11b6ae0, 0xc425e9f620, 0x11bcec0, 0xc420251040, 0xc42586e580, 0xc425576000, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cayleygraph/cayley/query/graphql/graphql.go:343 +0x1db6
github.com/cayleygraph/cayley/query/graphql.iterateObject(0x11b6ae0, 0xc425e9f620, 0x11bcec0, 0xc420251040, 0xc42663d7c8, 0xc4253b5480, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cayleygraph/cayley/query/graphql/graphql.go:343 +0x1db6
github.com/cayleygraph/cayley/query/graphql.(*Query).Execute(0xc425fcf200, 0x11b6ae0, 0xc425e9f620, 0x11bcec0, 0xc420251040, 0xc42001e000, 0xf90fe0, 0x1021900)
	/go/src/github.com/cayleygraph/cayley/query/graphql/graphql.go:373 +0x15e
github.com/cayleygraph/cayley/query/graphql.httpQuery(0x11b6ae0, 0xc425e9f620, 0x11bcec0, 0xc420251040, 0x7feb6dda3da0, 0xc425fce340, 0x7feb6dda3dc8, 0xc4253b4cc0)
	/go/src/github.com/cayleygraph/cayley/query/graphql/http.go:33 +0xa2
github.com/cayleygraph/cayley/internal/http.(*API).ServeV1Query(0xc42023b750, 0x11aff60, 0xc425fce340, 0xc426c06900, 0xc425fce320, 0x1, 0x1)
	/go/src/github.com/cayleygraph/cayley/internal/http/query.go:103 +0x974
github.com/cayleygraph/cayley/internal/http.(*API).ServeV1Query-fm(0x11aff60, 0xc425fce340, 0xc426c06900, 0xc425fce320, 0x1, 0x1)
	/go/src/github.com/cayleygraph/cayley/internal/http/http.go:154 +0x66
github.com/cayleygraph/cayley/internal/http.LogRequest.func1(0x11b3e60, 0xc425756700, 0xc426c06900, 0xc425fce320, 0x1, 0x1)
	/go/src/github.com/cayleygraph/cayley/internal/http/http.go:90 +0x2ad
github.com/cayleygraph/cayley/internal/http.CORS.func1(0x11b3e60, 0xc425756700, 0xc426c06900, 0xc425fce320, 0x1, 0x1)
	/go/src/github.com/cayleygraph/cayley/internal/http/http.go:149 +0xaf
github.com/cayleygraph/cayley/vendor/github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc4201b9900, 0x11b3e60, 0xc425756700, 0xc426c06900)
	/go/src/github.com/cayleygraph/cayley/vendor/github.com/julienschmidt/httprouter/router.go:344 +0x770
net/http.(*ServeMux).ServeHTTP(0x1b2e7c0, 0x11b3e60, 0xc425756700, 0xc426c06900)
	/usr/local/go/src/net/http/server.go:2340 +0x130
net/http.serverHandler.ServeHTTP(0xc420091e10, 0x11b3e60, 0xc425756700, 0xc426c06900)
	/usr/local/go/src/net/http/server.go:2697 +0xbc
net/http.(*conn).serve(0xc424f06140, 0x11b6a60, 0xc4253b4ac0)
	/usr/local/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2798 +0x27b
```

**Expected results:**
List of items.

**Output of `cayley version` or commit hash:**

```
Cayley version v0.7.5 [6ce5dd0]
```

**Environment details:**

Backend database: `(database and version)`
memstore

**Comment by iddan** [comment]
Can you provide a sample query and minimal dataset this issue is reproducible with?

**Comment by dennwc** [comment]
I found an issue and fixed it upstream. It may happen if a query specifies the value that doesn't exist in the database. Although without a query and a test data set I'm not sure in which part of the query this value should be to trigger this behavior.
