### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by rm-rf-etc** [cayleygraph/cayley#880]
**Description**
Installed Cayley using homebrew on macOS High Sierra v10.13.1, and received the following error output when trying to start Cayley.

**Steps to reproduce the issue:**
1. `brew install cayley`
2. `cayley http`

**Received results:**
`cayley http`
```
ERROR: logging before flag.Parse: E1022 13:58:18.830496   11472 cayley.go:142] The assets flag is deprecated as assets are provided as part of the binary.
I1022 13:58:18.830772   11472 command.go:805] Cayley version: 0.7.7 (dcf764f)
I1022 13:58:18.831442   11472 http.go:20] using backend "memstore"
I1022 13:58:18.831686   11472 command.go:826] listening on 127.0.0.1:64210, web interface at http://127.0.0.1:64210
2019/10/22 13:58:46 http: panic serving 127.0.0.1:50171: runtime error: invalid memory address or nil pointer dereference
goroutine 44 [running]:
net/http.(*conn).serve.func1(0xc00030ba40)
	/usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:1767 +0x139
panic(0x508f7c0, 0x6093b90)
	/usr/local/Cellar/go/1.13.1/libexec/src/runtime/panic.go:679 +0x1b2
html/template.(*Template).lookupAndEscapeTemplate(0x0, 0xc000149260, 0xa, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.13.1/libexec/src/html/template/template.go:144 +0x4e
html/template.(*Template).ExecuteTemplate(0x0, 0x54fa2e0, 0xc0003421c0, 0xc000149260, 0xa, 0x0, 0x0, 0x60b2040, 0x2)
	/usr/local/Cellar/go/1.13.1/libexec/src/html/template/template.go:133 +0x43
github.com/cayleygraph/cayley/internal/http.serveUI(0x551bde0, 0xc0003421c0, 0xc0001bac00, 0x0, 0x0, 0x0)
	/private/tmp/cayley-20191015-31941-1plgvxa/src/github.com/cayleygraph/cayley/internal/http/ui.go:35 +0x156
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc00014cac0, 0x551bde0, 0xc0003421c0, 0xc0001bac00)
	/private/tmp/cayley-20191015-31941-1plgvxa/pkg/mod/github.com/julienschmidt/httprouter@v1.2.0/router.go:334 +0x95e
net/http.(*ServeMux).ServeHTTP(0x60b2040, 0x551bde0, 0xc0003421c0, 0xc0001bac00)
	/usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2387 +0x1bd
net/http.serverHandler.ServeHTTP(0xc0003420e0, 0x551bde0, 0xc0003421c0, 0xc0001bac00)
	/usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc00030ba40, 0x55236e0, 0xc00014cc40)
	/usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2927 +0x38e
2019/10/22 13:58:47 http: panic serving 127.0.0.1:50172: runtime error: invalid memory address or nil pointer dereference
goroutine 31 [running]:
net/http.(*conn).serve.func1(0xc0003441e0)
	/usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:1767 +0x139
panic(0x508f7c0, 0x6093b90)
	/usr/local/Cellar/go/1.13.1/libexec/src/runtime/panic.go:679 +0x1b2
html/template.(*Template).lookupAndEscapeTemplate(0x0, 0xc00032aba0, 0xa, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.13.1/libexec/src/html/template/template.go:144 +0x4e
html/template.(*Template).ExecuteTemplate(0x0, 0x54fa2e0, 0xc000202380, 0xc00032aba0, 0xa, 0x0, 0x0, 0x60b2040, 0x2)
	/usr/local/Cellar/go/1.13.1/libexec/src/html/template/template.go:133 +0x43
github.com/cayleygraph/cayley/internal/http.serveUI(0x551bde0, 0xc000202380, 0xc000154500, 0x0, 0x0, 0x0)
	/private/tmp/cayley-20191015-31941-1plgvxa/src/github.com/cayleygraph/cayley/internal/http/ui.go:35 +0x156
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc00014cac0, 0x551bde0, 0xc000202380, 0xc000154500)
	/private/tmp/cayley-20191015-31941-1plgvxa/pkg/mod/github.com/julienschmidt/httprouter@v1.2.0/router.go:334 +0x95e
net/http.(*ServeMux).ServeHTTP(0x60b2040, 0x551bde0, 0xc000202380, 0xc000154500)
	/usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2387 +0x1bd
net/http.serverHandler.ServeHTTP(0xc0003420e0, 0x551bde0, 0xc000202380, 0xc000154500)
	/usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0003441e0, 0x55236e0, 0xc000092640)
	/usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2927 +0x38e
2019/10/22 13:58:47 http: panic serving 127.0.0.1:50175: runtime error: invalid memory address or nil pointer dereference
goroutine 50 [running]:
net/http.(*conn).serve.func1(0xc00039e000)
	/usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:1767 +0x139
panic(0x508f7c0, 0x6093b90)
	/usr/local/Cellar/go/1.13.1/libexec/src/runtime/panic.go:679 +0x1b2
html/template.(*Template).lookupAndEscapeTemplate(0x0, 0xc00032ac30, 0xa, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.13.1/libexec/src/html/template/template.go:144 +0x4e
html/template.(*Template).ExecuteTemplate(0x0, 0x54fa2e0, 0xc000202460, 0xc00032ac30, 0xa, 0x0, 0x0, 0x60b2040, 0x2)
	/usr/local/Cellar/go/1.13.1/libexec/src/html/template/template.go:133 +0x43
github.com/cayleygraph/cayley/internal/http.serveUI(0x551bde0, 0xc000202460, 0xc0001bad00, 0x0, 0x0, 0x0)
	/private/tmp/cayley-20191015-31941-1plgvxa/src/github.com/cayleygraph/cayley/internal/http/ui.go:35 +0x156
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc00014cac0, 0x551bde0, 0xc000202460, 0xc0001bad00)
	/private/tmp/cayley-20191015-31941-1plgvxa/pkg/mod/github.com/julienschmidt/httprouter@v1.2.0/router.go:334 +0x95e
net/http.(*ServeMux).ServeHTTP(0x60b2040, 0x551bde0, 0xc000202460, 0xc0001bad00)
	/usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2387 +0x1bd
net/http.serverHandler.ServeHTTP(0xc0003420e0, 0x551bde0, 0xc000202460, 0xc0001bad00)
	/usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc00039e000, 0x55236e0, 0xc00014cdc0)
	/usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2927 +0x38e
2019/10/22 13:58:52 http: panic serving 127.0.0.1:50176: runtime error: invalid memory address or nil pointer dereference
goroutine 47 [running]:
net/http.(*conn).serve.func1(0xc00030bae0)
	/usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:1767 +0x139
panic(0x508f7c0, 0x6093b90)
	/usr/local/Cellar/go/1.13.1/libexec/src/runtime/panic.go:679 +0x1b2
html/template.(*Template).lookupAndEscapeTemplate(0x0, 0xc0003b6080, 0xa, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.13.1/libexec/src/html/template/template.go:144 +0x4e
html/template.(*Template).ExecuteTemplate(0x0, 0x54fa2e0, 0xc0003c8000, 0xc0003b6080, 0xa, 0x0, 0x0, 0x60b2040, 0x2)
	/usr/local/Cellar/go/1.13.1/libexec/src/html/template/template.go:133 +0x43
github.com/cayleygraph/cayley/internal/http.serveUI(0x551bde0, 0xc0003c8000, 0xc000154600, 0x0, 0x0, 0x0)
	/private/tmp/cayley-20191015-31941-1plgvxa/src/github.com/cayleygraph/cayley/internal/http/ui.go:35 +0x156
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc00014cac0, 0x551bde0, 0xc0003c8000, 0xc000154600)
	/private/tmp/cayley-20191015-31941-1plgvxa/pkg/mod/github.com/julienschmidt/httprouter@v1.2.0/router.go:334 +0x95e
net/http.(*ServeMux).ServeHTTP(0x60b2040, 0x551bde0, 0xc0003c8000, 0xc000154600)
	/usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2387 +0x1bd
net/http.serverHandler.ServeHTTP(0xc0003420e0, 0x551bde0, 0xc0003c8000, 0xc000154600)
	/usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc00030bae0, 0x55236e0, 0xc000092700)
	/usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2927 +0x38e
2019/10/22 13:58:52 http: panic serving 127.0.0.1:50179: runtime error: invalid memory address or nil pointer dereference
goroutine 13 [running]:
net/http.(*conn).serve.func1(0xc000158b40)
	/usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:1767 +0x139
panic(0x508f7c0, 0x6093b90)
	/usr/local/Cellar/go/1.13.1/libexec/src/runtime/panic.go:679 +0x1b2
html/template.(*Template).lookupAndEscapeTemplate(0x0, 0xc000149330, 0xa, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.13.1/libexec/src/html/template/template.go:144 +0x4e
html/template.(*Template).ExecuteTemplate(0x0, 0x54fa2e0, 0xc0003422a0, 0xc000149330, 0xa, 0x0, 0x0, 0x60b2040, 0x2)
	/usr/local/Cellar/go/1.13.1/libexec/src/html/template/template.go:133 +0x43
github.com/cayleygraph/cayley/internal/http.serveUI(0x551bde0, 0xc0003422a0, 0xc0003f0000, 0x0, 0x0, 0x0)
	/private/tmp/cayley-20191015-31941-1plgvxa/src/github.com/cayleygraph/cayley/internal/http/ui.go:35 +0x156
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc00014cac0, 0x551bde0, 0xc0003422a0, 0xc0003f0000)
	/private/tmp/cayley-20191015-31941-1plgvxa/pkg/mod/github.com/julienschmidt/httprouter@v1.2.0/router.go:334 +0x95e
net/http.(*ServeMux).ServeHTTP(0x60b2040, 0x551bde0, 0xc0003422a0, 0xc0003f0000)
	/usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2387 +0x1bd
net/http.serverHandler.ServeHTTP(0xc0003420e0, 0x551bde0, 0xc0003422a0, 0xc0003f0000)
	/usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc000158b40, 0x55236e0, 0xc0003be080)
	/usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2927 +0x38e
2019/10/22 13:58:54 http: panic serving 127.0.0.1:50181: runtime error: invalid memory address or nil pointer dereference
goroutine 48 [running]:
net/http.(*conn).serve.func1(0xc00030bb80)
	/usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:1767 +0x139
panic(0x508f7c0, 0x6093b90)
	/usr/local/Cellar/go/1.13.1/libexec/src/runtime/panic.go:679 +0x1b2
html/template.(*Template).lookupAndEscapeTemplate(0x0, 0xc0003b6140, 0xa, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.13.1/libexec/src/html/template/template.go:144 +0x4e
html/template.(*Template).ExecuteTemplate(0x0, 0x54fa2e0, 0xc0003c80e0, 0xc0003b6140, 0xa, 0x0, 0x0, 0x60b2040, 0x2)
	/usr/local/Cellar/go/1.13.1/libexec/src/html/template/template.go:133 +0x43
github.com/cayleygraph/cayley/internal/http.serveUI(0x551bde0, 0xc0003c80e0, 0xc0003f0100, 0x0, 0x0, 0x0)
	/private/tmp/cayley-20191015-31941-1plgvxa/src/github.com/cayleygraph/cayley/internal/http/ui.go:35 +0x156
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc00014cac0, 0x551bde0, 0xc0003c80e0, 0xc0003f0100)
	/private/tmp/cayley-20191015-31941-1plgvxa/pkg/mod/github.com/julienschmidt/httprouter@v1.2.0/router.go:334 +0x95e
net/http.(*ServeMux).ServeHTTP(0x60b2040, 0x551bde0, 0xc0003c80e0, 0xc0003f0100)
	/usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2387 +0x1bd
net/http.serverHandler.ServeHTTP(0xc0003420e0, 0x551bde0, 0xc0003c80e0, 0xc0003f0100)
	/usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc00030bb80, 0x55236e0, 0xc0003be100)
	/usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2927 +0x38e
2019/10/22 13:59:24 http: panic serving 127.0.0.1:50182: runtime error: invalid memory address or nil pointer dereference
goroutine 66 [running]:
net/http.(*conn).serve.func1(0xc000344320)
	/usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:1767 +0x139
panic(0x508f7c0, 0x6093b90)
	/usr/local/Cellar/go/1.13.1/libexec/src/runtime/panic.go:679 +0x1b2
html/template.(*Template).lookupAndEscapeTemplate(0x0, 0xc0003b61d0, 0xa, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.13.1/libexec/src/html/template/template.go:144 +0x4e
html/template.(*Template).ExecuteTemplate(0x0, 0x54fa2e0, 0xc0003c81c0, 0xc0003b61d0, 0xa, 0x0, 0x0, 0x60b2040, 0x2)
	/usr/local/Cellar/go/1.13.1/libexec/src/html/template/template.go:133 +0x43
github.com/cayleygraph/cayley/internal/http.serveUI(0x551bde0, 0xc0003c81c0, 0xc000154800, 0x0, 0x0, 0x0)
	/private/tmp/cayley-20191015-31941-1plgvxa/src/github.com/cayleygraph/cayley/internal/http/ui.go:35 +0x156
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc00014cac0, 0x551bde0, 0xc0003c81c0, 0xc000154800)
	/private/tmp/cayley-20191015-31941-1plgvxa/pkg/mod/github.com/julienschmidt/httprouter@v1.2.0/router.go:334 +0x95e
net/http.(*ServeMux).ServeHTTP(0x60b2040, 0x551bde0, 0xc0003c81c0, 0xc000154800)
	/usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2387 +0x1bd
net/http.serverHandler.ServeHTTP(0xc0003420e0, 0x551bde0, 0xc0003c81c0, 0xc000154800)
	/usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc000344320, 0x55236e0, 0xc000092840)
	/usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2927 +0x38e
```

**Output of `cayley version` or commit hash:**
```
ERROR: logging before flag.Parse: E1022 14:07:59.737089   11757 cayley.go:142] The assets flag is deprecated as assets are provided as part of the binary.
Cayley version: 0.7.7
Git commit hash: dcf764f
```

**Comment by rm-rf-etc** [comment]
Found mention of this issue in discourse. Then uninstalled Cayley from homebrew and built instead from source. Issue was gone.
